## Remember that the solutions need to be saved int variable provided.

In [1]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [1]:
import numpy as np
a = np.random.uniform(size = (10,10))
print(a)
print(np.amin(a))
print(np.amax(a))

[[0.64338994 0.45151535 0.19878269 0.04927551 0.76609425 0.82715304
  0.12401574 0.37058843 0.40464803 0.76502228]
 [0.07285197 0.27576378 0.42560766 0.99329545 0.97405304 0.38080592
  0.01236312 0.09428024 0.01457608 0.50483343]
 [0.67663811 0.09528849 0.65850376 0.67628484 0.6303155  0.77069465
  0.07939629 0.61898311 0.52065809 0.73771935]
 [0.33104108 0.61238696 0.01740682 0.94643476 0.14536306 0.46213033
  0.01907983 0.04232036 0.92692103 0.44021934]
 [0.78221783 0.47958974 0.68893455 0.11552719 0.71739182 0.05696545
  0.53037709 0.08396891 0.61705589 0.78763082]
 [0.5047699  0.0790004  0.14020973 0.80134107 0.15561298 0.3751436
  0.12485527 0.27079988 0.34000649 0.43048817]
 [0.38016989 0.89175419 0.68064666 0.99378532 0.27600176 0.47549515
  0.21709852 0.72705369 0.61167508 0.86479684]
 [0.88316982 0.63058252 0.62461254 0.8334604  0.23198552 0.26953757
  0.53100435 0.00457391 0.78741347 0.9744948 ]
 [0.08662805 0.44256803 0.74885487 0.45158636 0.11771088 0.08716392
  0.98610788 

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [2]:
import numpy as np
a = np.ones(25)
print(a)
b = a.reshape((5,5))
print(b)

b[1:4,1:4] = 0 # first 1:4 is for rows and second one is for columns.
print(b)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**34. How to get all the dates corresponding to the month of July 2016**

In [3]:
import numpy as np
a = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [4]:
import numpy as np
a = np.array([1,4,54,56])
b= np.array([1,4,54,56])
print(a)
print(b)
print(np.array_equal(a,b))

c = np.random.uniform(size=(5))
d = np.random.uniform(size=5)
print(c)
print(d)
print(np.allclose(c,d))

[ 1  4 54 56]
[ 1  4 54 56]
True
[0.60358165 0.30894541 0.98726442 0.59076643 0.30927685]
[0.80177937 0.07299585 0.22115569 0.78655506 0.46169453]
False


**72. How to swap two rows of an array?** 

In [5]:
a = np.arange(15)
b = a.reshape(5,3)
print(b)
b[[0,1]] = b[[1,0]]
print(b)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 3  4  5]
 [ 0  1  2]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


**75. How to compute averages using a sliding window over an array?**